#!/bin/bash

set -euo pipefail
# shellcheck source=./framework.sh
source "${BASE_DIR}/framework.sh"

cores="$(sensors | grep 'Core')"

text=""
while IFS= read -r line; do
    current=$(echo "${line}" | awk '{ print substr($3, 2, length($3) - 4) }')
    high=$(echo "${line}" | awk '{ print substr($8, 2, length($8) - 4) }')
    critical=$(echo "${line}" | awk '{ print substr($11, 2, length($11) - 4) }')

    if [[ "${high}" == "${critical}" ]]; then
        high=$(bc -l <<< "${high} - 20")
    fi

    text+="$(print_color "${current}°C" "${current}" "${high}" "${critical}"), "
done <<< "${cores}"

print_columns "Temperatures" "${text::-2}"
